-- Phase 1 multi-tenant foundation: organizations table.
-- slug/invite_code are generated by the edge function at signup time, not here.
create table if not exists organizations (
  org_id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  invite_code text unique not null,
  created_at timestamptz not null default now()
);
